api/urls.py
from api.views import category_list
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('category/', category_list),
]

app/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('sitio.urls', 'sitio'), namespace='bases')),
    path('sitio/', include(('sitio.urls', 'sitio'), namespace='sitio')),
    path('', include('api.urls')),
]

sitio/urls.py
from django.urls.conf import path
from sitio import views as sitio_views

from django.contrib import admin
from django.urls import path, include
#from . import settings
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', sitio_views.index, name='index'),
    path('galeria', sitio_views.galeria, name='galeria'),
    #path('productos', sitio_views.productos, name='productos'),
    path('productos', sitio_views.productos, name='productos'),
    path('upload_image', sitio_views.upload_image, name='upload_image'),
    path('image_gallery', sitio_views.image_gallery, name='image_gallery'),
    path('puntos_ventas', sitio_views.puntos_ventas, name='puntos_ventas'),
    path('Galeria', sitio_views.slider, name='galeriaProductos'),
    # path('slider/<int:pk>', sitio_views.ProductSlider.as_view(),
    #      name='Images_Product'),
    path('slider2/<int:pk>/', sitio_views.slider2, name='ImagesProduct'),

    path('about', sitio_views.about, name='about'),
    path('contact', sitio_views.contact, name='contact'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/pages/base copy.html
{% load static %}
<!DOCTYPE html>
<html lang="">
<head>
<title>Bici Chocolate</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
<link rel="stylesheet" href="{% static 'base/css/layout.css' %}">
<link rel="shortcut icon" type="image/png" href="{% static 'base/img/favicon.ico' %}"/>

  <script type="text/javascript;" src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script type="text/javascript;" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script type="text/javascript;" src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script type="text/javascript;" src="{% static 'base/js/tools.js' %}"></script>

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'base/css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'base/css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'base/css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'base/css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'base/css/galery.css' %}" type="text/css"

    <!-- custom js & css -->
    <script type="text/javascript;" src={% static 'base/js/main.js' %} defer></script>
    <link type="text/css;" rel="stylesheet" href={% static 'base/css/style2.css' %}>

  <!--Jquery-->
  <script type="text/javascript;" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <!--Floating WhatsApp css-->
  <link rel="stylesheet" href="https://rawcdn.githack.com/rafaelbotazini/floating-whatsapp/3d18b26d5c7d430a1ab0b664f8ca6b69014aed68/floating-wpp.min.css">
  <!--Floating WhatsApp javascript-->
  <script type="text/javascript;" src="https://rawcdn.githack.com/rafaelbotazini/floating-whatsapp/3d18b26d5c7d430a1ab0b664f8ca6b69014aed68/floating-wpp.min.js"></script>  

</head>
<body id="top">
{% block top_bar %}
  
<div class="wrapper row0">
  <div id="topbar" class="hoc clear"> 
    <div class="fl_right">
      <ul class="nospace">
        <ul class="faico clear">
          <li><a class="faicon-facebook" href="https://www.facebook.com/bicichocolate" target="blank"><i class="fa fa-facebook"></i></a></li>
          <li><a class="faicon-instagram" href="https://www.instagram.com/bicichocolate_artesanal/?hl=es-la" target="blank"><i class="fa fa-instagram"></i></a></li>
          <li style="font-family: Playfair Display;"><i class="fa fa-phone"></i> (506) 8856 9415</li>
          <li style="font-family: Playfair Display;"><i class="fa fa-envelope-o"></i> info@bicichocolate.cr</li>
      </ul>
    </div>
  </div>
</div>
<div class="wrapper bgded overlay" style="background-image:url('{% static 'base/img/backgrounds/bg02.png' %}');">

  <header id="header" class="hoc clear"> 
    <nav id="mainav" class="fl_right">      
      <ul class="clear">
        <li style="font-family: Copperplate;"><a href="{% url 'sitio:index' %}"><i class="fa fa-lg fa-home"></i></a></li>        
        <li style="font-family: Copperplate;" class="active"><a href="{% url 'sitio:index' %}">Inicio</a></li>
        <li style="font-family: Copperplate;"><a href="{% url 'sitio:about' %}">Sobre Nosotros</a></li>
        <li style="font-family: Playfair Display;"><a href="{% url 'sitio:productos' %}">Productos</a></li>
        <li style="font-family: Copperplate;"><a href="{% url 'sitio:image_gallery' %}">Galeria</a></li>        
        <li style="font-family: Playfair Display;"><a href="{% url 'sitio:puntos_ventas' %}">Puntos de venta</a></li>
        <li style="font-family: Copperplate;"><a href="{% url 'sitio:galeriaProductos' %}">Galeria Producto</a></li>
        <li style="font-family: Playfair Display;"><a href="{% url 'sitio:contact' %}">Seguir en contacto</a></li>
      </ul>
    </nav>
  </header>
</div>
<div style="margin-bottom: 1rem;">
  
</div>
{% endblock top_bar %}

{% block page_content %}
<div class="wrapper bgded" style="height:400px; width:100%; background-image:url('{% static 'base/img/backgrounds/Bicichocolate_09.png' %}');">
  <div id="pageintro" class="hoc clear"> 
    <article>
      <p style="color: chocolate; font-family: Playfair Display; font-size: 2rem;"> ¡Para los que disfrutan del</p>
      <p style="color: chocolate; font-family: Copperplate; font-size: 5rem;">Autentico sabor!...</p>
    </article>
  </div>
</div>
<br>
<br>
<br>
<div class="wrapper row3">
  <main class="hoc container clear"> 
    <!-- main body -->
    <section id="introblocks">
      <div class="sectiontitle">
        <h6 class="heading">Estos son nuestros pilares</h6>
        <p>Nullam tincidunt ex vel volutpat accumsan ut lobortis metus</p>
      </div>
      <ul class="nospace btmspace-80 group">
        <li class="one_third first">
          <article><i class="fa fa-leaf"></i>
            <h6 class="heading font-x1"><a href="#">Finca Bosque de Chocolate</a></h6>
            <p>Parte de la fruta de cacao es producida en nuestra finca en Puerto Viejo de Sarapiquí de Heredia, 
              donde tenemos una finca que respeta y protege el medio ambiente mediante la utilización de técnicas 
              agrícolas naturales y ancestrales. Nuestra finca se llama “Bosque de chocolate” y como principal 
              objetivo tiene la protección de 3 hectáreas de bosque secundario y el establecimiento de un 
              Modelo Diversificado Agro-forestal cuyo cultivo estrella es el Cacao.
              El proyecto tiene 7 años de vida y cuenta con un terreno de 7 hectáreas aproximadamente.</p>
          </article>
        </li>
        <li class="one_third">
          <article><i class="fa fa-cubes"></i>
            <h6 class="heading font-x1"><a href="#">Nuestros Chocolates</a></h6>
            <p>El Cacao lo transformamos en chocolate en nuestra empresa ubicada en Barva de Heredia, Costa Rica. 
              Hacemos productos derivados del Cacao y además Chocolates de diferentes porcentajes de pureza del Cacao, 
              esto mediante el uso de Bici-Máquinas y técnicas artesanales. Utilizamos azúcar orgánico y no utilizamos 
              derivados lácteos en la mayoría de nuestros productos y del todo NO añadimos preservantes ni aditivos. 
            </p>
          </article>
        </li>
        <li class="one_third">
          <article><i class="fa fa-bicycle"></i>
            <h6 class="heading font-x1"><a href="#">Bici-Máquinas</a></h6>
            <p>Son máquinas impulsadas con fuerza de pedaleo. Representan una alternativa económica, saludable y amigable
              con el ambiente, ya que no requieren de energía eléctrica para funcionar. Son una herramienta que sirve para 
              apoyar la economía familiar, obteniendo una capacidad más alta que la manual. 
              Existen muchos tipos de estas máquinas para diferentes necesidades. En Bici-Chocolate utilizamos la Bici-moledora, 
              la Bici-Licuadora y la Bici-Tostadora para la elaboración de nuestros productos. También ofrecemos el servicio de 
              elaboración y venta de más de 30 tipos de Bici-máquinas.
            </p>
          </article>
        </li>
      </ul>
    </section>
    <hr class="btmspace-80">
    <section>
      <div class="sectiontitle">
        <h6 class="heading">Que nos distingue</h6>
        <p>Productos de la más alta calidad, gran sabor, 100% natural.</p>
      </div>
      <ul class="nospace group overview">
        <li class="one_third">
          <figure><a href="#"><img style="border: 2px solid black;" src="{% static 'base/img/gallery/Bicichocolate_18.jpg' %}" alt=""></a>
            <figcaption>
              <h6 class="heading">Cuidados procesos de producción</h6>
              <p>Con lo que optenemos materias primas de excelente calidad.</p>
            </figcaption>
          </figure>
        </li>
        <li class="one_third">
          <figure><a href="#"><img style="border: 2px solid black;" src="{% static 'base/img/gallery/Bicichocolate_58.jpg' %}" alt=""></a>
            <figcaption>
              <h6 class="heading">Cuidadosa producción artesanal</h6>
              <p>Cuidando cada detalle durante cada lote de producción, es logramos y mantenemos nuestra calidad.</p>
            </figcaption>
          </figure>
        </li>
        <li class="one_third">
          <figure><a href="#"><img style="border: 2px solid black;" src="{% static 'base/img/gallery/Bicichocolate_68.jpg' %}" alt=""></a>
            <figcaption>
              <h6 class="heading">Fusce facilisis congue</h6>
              <p>Sapien sit amet tempor nisl mollis sed sed tristique nunc pretium mi.</p>
            </figcaption>
          </figure>
        </li>
      </ul>
    </section>
    <!-- / main body -->
    <div class="clear"></div>
  </main>
</div>
<div class="wrapper bgded overlay" style="background-image:url('{% static 'base/img/backgrounds/bg02.png' %}');">
  <article class="hoc cta clear"> 
    <h6 class="three_quarter first">Del Cacao a nuestro paladar</h6>
    <footer class="one_quarter"><a class="btn" href="#">Neque mauris nunc &raquo;</a></footer>
  </article>
</div>
<div class="wrapper row3">
  <figure class="hoc container clear clients"> 
    <figcaption class="sectiontitle">
      <h6 class="heading">Nullam scelerisque orci eu</h6>
      <p>Pulvinar sodales suspendisse in purus vel massa fermentum</p>
    </figcaption>
    <ul class="nospace group">
      <li class="one_quarter first"><a href="#"><img style="border: 2px solid chocolate;" src="{% static 'base/img/gallery/Bicichocolate_170.jpg' %}" alt=""></a></li>
      <li class="one_quarter"><a href="#"><img style="border: 2px solid chocolate;"src="{% static 'base/img/gallery/Bicichocolate_189.jpg' %}" alt=""></a></li>
      <li class="one_quarter"><a href="#"><img style="border: 2px solid chocolate;"src="{% static 'base/img/gallery/Bicichocolate_66.jpg' %}" alt=""></a></li>
      <li class="one_quarter"><a href="#"><img style="border: 2px solid chocolate;"src="{% static 'base/img/gallery/Bicichocolate_04.jpg' %}" alt=""></a></li>
    </ul>
  </figure>
</div>
{% endblock page_content %}

{% block footer %}
  

{% endblock footer %}
</div>
<div class="wrapper bgded overlay" style="background-image:url('{% static 'base/img/backgrounds/bg02.png' %}');">
    <div id="copyright" class="hoc clear"> 
        <p class="fl_left">Copyright &copy; 2021 - All Rights Reserved - <a href="#">bicichocolate.net</a></p>
    </div>
</div>

<div class="modal fade" id="popup"></div>

</div>
<!-- End Footer Background Image Wrapper -->
<a id="backtotop" href="#top"><i class="fa fa-chevron-up"></i></a>
<!-- JAVASCRIPTS -->
<script type="text/javascript;" src="{% static 'base/js/jquery.min.js' %}"></script>
<script type="text/javascript;" src="{% static  'base/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script type="text/javascript;" src="{% static 'base/js/jquery.backtotop.js' %}"></script>
<script type="text/javascript;" src="{% static 'base/js/jquery.mobilemenu.js' %}"></script>

<!--
  <script type="text/javascript;" src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
-->

<script type="text/javascript;" src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" ></script>
<script type="text/javascript;" src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"></script>



<!-- Division 
  <!-- Bootstrap core JavaScript
  <script src="{% static  'base/vendor/jquery/jquery.min.js' %}"></script> 
  -->

  <!-- Core plugin JavaScript
  <script src="{% static  'base/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
  -->

  <!-- Page level plugins -->
  <script type="text/javascript;" src="{% static 'base/vendor/datatables/jquery.dataTables.min.js'%}"></script>
  <script type="text/javascript;" src="{% static 'base/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

  <script type="text/javascript;" src="{% static 'base/vendor/jquery_confirm/jquery-confirm.min.js' %}"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"></script>

  <script src="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table.min.js"></script>
  <script src="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table-locale-all.min.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/js/select2.min.js"></script>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>


<script>
  $(document).ready(function () {
    jQuery.datetimepicker.setLocale('es');
  });
</script>


<div class="modal fade" id="popup"></div> 


{% block control_modal%}

  <script>
    function abrir_modal(url)
    {
      $("#popup").load(url, function(){
        $(this).modal({
          backdrop:'static',
          keyboard: false
        })
        $(this).modal('show');
      });
      return false;
    }

    function cerrar_modal()
    {
      $('#popup').modal('hide');
      return false;
    }

    function mensaje(msg,color='green')
    {
      if (color=="success")
      {
        color="green";
      }
      if (color=="error")
      {
        color="red";
      }


      $.alert({
        title:'',
        theme:'material',
        type:color,
        content:msg
      });
    }

    {% if messages %}
      {% for message in messages %}
        console.log("{{ message.tags }}");
        mensaje("{{ message }}","{{ message.tags }}");
      {% endfor %}
    {% endif %}

  </script>

{% endblock%}
{% block js_page %} {% endblock %}
</body>
</html>