api/urls.py
from api.views import category_list
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('category/', category_list),
]

app/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('sitio.urls', 'sitio'), namespace='bases')),
    path('sitio/', include(('sitio.urls', 'sitio'), namespace='sitio')),
    path('', include('api.urls')),
]

sitio/urls.py
from django.urls.conf import path
from sitio import views as sitio_views

from django.contrib import admin
from django.urls import path, include
#from . import settings
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', sitio_views.index, name='index'),
    path('galeria', sitio_views.galeria, name='galeria'),
    #path('productos', sitio_views.productos, name='productos'),
    path('productos', sitio_views.productos, name='productos'),
    path('upload_image', sitio_views.upload_image, name='upload_image'),
    path('image_gallery', sitio_views.image_gallery, name='image_gallery'),
    path('puntos_ventas', sitio_views.puntos_ventas, name='puntos_ventas'),
    path('Galeria', sitio_views.slider, name='galeriaProductos'),
    # path('slider/<int:pk>', sitio_views.ProductSlider.as_view(),
    #      name='Images_Product'),
    path('slider2/<int:pk>/', sitio_views.slider2, name='ImagesProduct'),

    path('about', sitio_views.about, name='about'),
    path('contact', sitio_views.contact, name='contact'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sitio/models.py
import datetime
from django.db import models
from sorl.thumbnail import ImageField

# Create your models here.


class PointSale(models.Model):
    name = models.CharField(max_length=30, blank=False, unique=True)
    direction = models.CharField(max_length=250, blank=False)
    telephone = models.CharField(max_length=12)
    logo = models.ImageField(upload_to='logo',blank=True)
    is_active = models.BooleanField(default=True)
    
    def __str__(self):
        return '{}'.format(self.name)

    def save(self):
        self.name = self.name.upper()
        super(PointSale, self).save()

    class Meta:
        verbose_name_plural = "PointSales"


class Category(models.Model):
    name = models.CharField(max_length=30, blank=False, unique=True)
    description = models.CharField(max_length=250, blank=False)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return '{}'.format(self.name)

    def save(self):
        self.name = self.name.upper()
        super(Category, self).save()

    class Meta:
        verbose_name_plural = "Categorys"


class ChocolateType(models.Model):
    name = models.CharField(max_length=30, blank=False, unique=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return '{}'.format(self.name)

    def save(self):
        self.name = self.name.upper()
        super(ChocolateType, self).save()

    class Meta:
        verbose_name_plural = "Types"


class Flavor(models.Model):
    name = models.CharField(max_length=30, blank=False, unique=True)
    description = models.CharField(max_length=50, blank=False)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return '{}'.format(self.name)

    def save(self):
        self.name = self.name.upper()
        super(Flavor, self).save()

    class Meta:
        verbose_name_plural = "Flavors"
              
class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    chocolateType = models.ForeignKey(ChocolateType, on_delete=models.CASCADE)
    flavor = models.ForeignKey(Flavor, on_delete=models.CASCADE)
    name = models.CharField(max_length=30, blank=False, unique=True)
    description = models.CharField(max_length=250, blank=False)
    imagen = models.ImageField(upload_to='gallery', blank=True)
    price = models.FloatField(default=0)
    is_active = models.BooleanField(default=True)
    year_of_validity = models.DateField()
    

    def __str__(self):
        return '{}'.format(self.name)

    @property
    def imageURL(self):
        try:
            url = self.featured.url
        except:
            url = ''
        print('URL:', url)
        return url

    @property
    def only_year(self):
        return self.year_of_validity.strftime('%Y')

    '''
    @admin.display
        def colored_name(self):
            return format_html(
                '<span style="color: #{};">{} {}</span>',
                self.color_code,
                self.first_name,
                self.last_name,
            )
    '''        
                    
    def save(self):
        self.name = self.name.upper()
        super(Product, self).save()

    class Meta:
        verbose_name_plural = "Products"


class Image(models.Model):
    image = models.ImageField(
        upload_to='gallery')
    name = models.CharField(max_length=200)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.name)

    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        print('URL:', url)
        return url



YEAR_CHOICES = []
for r in range(2015, (datetime.datetime.now().year+2)):
    YEAR_CHOICES.append((r,r))

class ApproveStopModelField(models.DateField):
    pass

class PruebaFecha(models.Model):
    # Other fields
    year_of_validity = models.DateField('Year of Validity', null=True, blank=True)

    '''
    @property
    def yaer_only(self):
        return self.year_of_validity.strftime('%Y')
    '''    

sitio/forms.py
from datetime import datetime
from django import forms
from django.core.exceptions import ValidationError
from django.forms import fields
from django.forms.widgets import Widget
from .models import *
from django.contrib.admin.widgets import AdminDateWidget, AdminTimeWidget, AdminSplitDateTime

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['image', 'name']

class ProductForm(forms.ModelForm):     

    class Meta:
        model = Product
        fields = ['category','chocolateType','flavor','name','description','imagen','price','is_active','year_of_validity']
        #exclude =['year_of_validity']
        #fields = '__all__'


from django.utils.dateparse import parse_date

class PruebaFechaAdminForm(forms.ModelForm):
    YEAR_CHOICES = []
    for r in range(2015, (datetime.datetime.now().year+2)):
        YEAR_CHOICES.append((r,r))

    tmp_year_validity = forms.ChoiceField(choices=YEAR_CHOICES)    
                                     

    def save(self, *args, **kwargs):
    
        tmp = self.cleaned_data['tmp_year_validity']
        
        tmp_PruebaFecha = super(PruebaFechaAdminForm,self).save(commit=False)        
        temp_date = parse_date(str(str(tmp) + "-01-02"))                
        
        tmp_PruebaFecha.year_of_validity = temp_date
        tmp_PruebaFecha.save()
        return tmp_PruebaFecha
        
        #super(PruebaFechaAdminForm, self).save(*args, **kwargs)                        

 
    class Meta:
        model = PruebaFecha
        exclude = ['year_validity']

sitio/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from django.views import generic
from .models import *
from .forms import *
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView, View
from django.views import generic
from django.urls import reverse_lazy
from django.core import serializers
from django.http import JsonResponse


# Create your views here.


def index(request):
    return render(request, 'sitio/index.html')


def about(request):
    return render(request, 'sitio/about.html')


def producto(request):
    productos = Product.objects.all()
    return render(request, 'sitio/product.html', {'products': productos})


def productos(request):
    productos = Product.objects.all()
    return render(request, 'sitio/products.html', {'products': productos})


def slider(request):
    product = Product.objects.first()
    context = {'product': product}
    return render(request, 'sitio/productsimage.html', context)
    # return render(request, 'sitio/modal.html', context)


# class ProductSlider(generic.ListView):
#     model = Product

#     product = Product.objects.first()
#     context = {'product': product}

#     template_name = "sitio/modal.html"
#     context_object_name = "obj"
#     success_url = reverse_lazy("sitio:productos")
#     success_message = "Listado exitoso"


def slider2(request, pk):
    product = Product.objects.get(id=pk)
    context = {'product': product}
    return render(request, 'sitio/productsimage.html', context)


def contact(request):
    return render(request, 'sitio/contact.html')


def galeria(request):
    return render(request, 'sitio/galeria.html')


def upload_image(request):
    if request.method == 'GET':
        return render(request, 'sitio/upload_image.html')
    elif request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            new_image = Image(image=form.cleaned_data["image"],
                              name=form.cleaned_data["name"]
                              )
            new_image.save()
            return HttpResponseRedirect('/sitio/image_gallery')


def image_gallery(request):
    images = Image.objects.all()
    return render(request, 'sitio/image_gallery.html', {'images': images})

def puntos_ventas(request):
    puntosventas = PointSale.objects.all()
    return render(request, 'sitio/pos.html', {'puntosventas': puntosventas})

class PictureView(View):
    def get(self, request):
        qs = Product.objects.all()
        data = serializers.serialize('json', qs)
        return JsonResponse({'data': data}, safe=False)

sitio/templates/sitio/about.html
{% extends 'base2.html' %}
{% load static %}

{% block page_content %}


<div class="container">

    <div class="row">
      <footer>
        <ul class="nospace inline pushright">
          <figure><a href="#"><img style="align-items: center;" src="{% static 'base/img/LogoTransparente240X240.png' %}" alt=""></a>
          </figure>         
        </ul>
      </footer>
      <video autoplay="true" width="800" height="374" loop="true">
        <source src="{% static 'base/video/BicichocolatePresentacion.mp4' %}" type="video/mp4" />
        <source src="{% static 'base/video/BicichocolatePresentacion.ogv' %}" type="video/ogg" />
        <source src="{% static 'base/video/BicichocolatePresentacion.webm' %}" type="video/webm">
      </video> 
  
    </div>
  </div>
  <div class="wrapper row2">
    <section class="hoc container clear testimonials"> 
      <div class="sectiontitle">
        <h6 class="heading">Efficitur posuere tellus non</h6>
        <p>Mattis turpis praesent dignissim et libero non luctus vivamus</p>
      </div>
      <ul class="nospace group btmspace-80">
        <li class="one_third first">
          <blockquote>Imperdiet libero ac sapien facilisis ultricies aliquam gravida ligula quis commodo interdum purus felis rutrum velit non tincidunt arcu orci eget nulla etiam laoreet volutpat mollis mauris</blockquote>
          <figure class="clear"><img class="circle" style="height: 50%; width:50%" src="{% static 'base/img/gallery/andresulate.jpg' %}" alt="">
            <figcaption>
              <h6 class="heading">Andre Ulate</h6>
              <em>Consultant</em></figcaption>
          </figure>
        </li>
        <li class="one_third">
          <blockquote>Et tellus nibh nullam sit amet mauris consequat vehicula velit non aliquam erat maecenas egestas dui et velit viverra in tincidunt neque consectetur quisque metus arcu suscipit rutrum euismod</blockquote>
          <figure class="clear"><img class="circle" style="height: 50%; width:50%" src="{% static 'base/img/gallery/danielpacheco.jpg' %}" alt="">
            <figcaption>
              <h6 class="heading">Daneil Pacheco</h6>
              <em>Director</em></figcaption>
          </figure>
        </li>
        <li class="one_third">
          <blockquote>Consequat venenatis vestibulum enim phasellus id molestie mi nec vulputate massa phasellus ut ligula hendrerit lobortis nibh ac laoreet sapien morbi id sagittis nulla vulputate fringilla felis</blockquote>
          <figure class="clear"><img class="circle" style="height: 50%; width:50%" src="{% static 'base/img/60x60.png' %}" alt="">
            <figcaption>
              <h6 class="heading">June Doe</h6>
              <em>Marketing</em></figcaption>
          </figure>
        </li>
      </ul>
    </section>
  </div>
    
{% endblock %}

{% block footer %}
{% endblock %}

sitio/templates/sitio/contact.html
{% extends 'base2.html' %}
{% load static %}

{% block page_content %}
    
<section class="contact spad">
    <div class="container">
        <div class="contact__text">
            <div class="row">
                <div class="col-lg-6 col-md-6">
                    <div class="contact__map">
                        <iframe
                            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3928.995868927876!2d-84.12173538584761!3d10.017198792839386!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8fa0fb16cadbfff5%3A0xac18ffbca2833c62!2sBicichocolate!5e0!3m2!1ses-419!2scr!4v1614891095932!5m2!1ses-419!2scr"
                            height="350" style="border:0;" allowfullscreen="" aria-hidden="false"
                            tabindex="0"></iframe>
                    </div>
                    <div class="contact__widget">
                        <ul>
                            <li>
                                <i class="fa fa-map-marker"></i>
                                <span>Heredia, Barva, Jardines de Santa Lucia, Calle Las Pomas</span>
                            </li>
                            <li>
                                <i class="fa fa-mobile"></i>
                                <span>Teléfono: 8481-1367</span>
                            </li>
                            <li>
                                <i class="fa fa-envelope-o"></i>
                                <span>Email: info@bicichocolate.net</span>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="contact__form">
                        <div class="contact__form__title">
                            <h2>Nos interesa conocerlo</h2>
                            <p>Nos gustaria atender sus inquietudes, para lo cual ponemos a su disposición este formulario, además 
                                puedes seguirnos en nuestras redes sociales.
                            </p>
                        </div>
                        <form action="#">
                            <input type="text" placeholder="Nombre">
                            <input type="text" placeholder="Email">
                            <input type="text" placeholder="Teléfono">
                            <textarea placeholder="Message"></textarea>
                            <button type="submit" class="site-btn">Enviar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Contact Section End -->

<!-- Footer Section Begin -->
<!-- Search Begin -->
<div class="search-model">
    <div class="h-100 d-flex align-items-center justify-content-center">
        <div class="search-close-switch">+</div>
        <form class="search-model-form">
            <input type="text" id="search-input" placeholder="Search here.....">
        </form>
    </div>
</div>
<!-- Search End -->

<!-- Js Plugins -->
<script src="js/jquery-3.3.1.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/jquery.slicknav.js"></script>
<script src="js/owl.carousel.min.js"></script>
<script src="js/main.js"></script>

{% endblock page_content %}}

sitio/templates/sitio/galeria.html
{% extends 'base2.html' %}
{% load static %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <style>
  /* Make the image fully responsive */
  .carousel-inner img {
    width: 100%;
    height: 100%;
  }
  </style
{% block page_content %}

<div class="container-md pt-3 bg-dark text-dark">
    <div class="row">        
        {% for image in images %}     
            <div class="col-4;">
                <div class="card ml-4 mr-2 mt-2 mb-2" style="width:25rem; height:35rem;">
                    <img class="card-img-top ml-2 mt-2" src="{{image.image.url}}" alt="Card image" style="image-rendering: auto; align-self:center; height:300px; width:300px">
                    <h4 class="card-title ml-2 mt-1">{{image.name}}</h4>
                </div>
            </div>
        {% endfor %}
    </div>
</div> 


<div class="container mt-3">

    <h2>Carousel</h2>
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
    
      <!-- Indicators -->
      <ul class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ul>
      
      <!-- The slideshow -->
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="la.jpg" alt="Los Angeles" width="1100" height="500">
        </div>
        <div class="carousel-item">
          <img src="chicago.jpg" alt="Chicago" width="1100" height="500">
        </div>
        <div class="carousel-item">
          <img src="ny.jpg" alt="New York" width="1100" height="500">
        </div>
      </div>
      
      <!-- Left and right controls -->
      <a class="carousel-control-prev" href="#myCarousel" data-slide="prev">
        <span class="carousel-control-prev-icon"></span>
      </a>
      <a class="carousel-control-next" href="#myCarousel" data-slide="next">
        <span class="carousel-control-next-icon"></span>
      </a>
    </div>
    
    </div>
    
{% endblock %}

{% block footer %}
{% endblock footer %}

sitio/templates/sitio/image_gallery.html
{% extends 'base2.html' %}
{% load static %}


  {% block page_content %}
    <div class="container-md pt-3 bg-dark text-dark">
      <div class="row">        
          {% for image in images %}     
              <div class="col-4;">
                <div class="card ml-4 mr-2 mt-2 mb-2" style="width:25rem; height:35rem;">
                      <h4 class="card-title ml-2 mt-1">{{image.name}}</h4>
                      <img class="card-img-top ml-2 mt-2" src="{{image.image.url}}" alt="Card image" 
                        style="image-rendering: auto; align-self:center; height:50%; width:auto">
                  </div>
              </div>
          {% endfor %}
      </div>
  </div>  
  {% endblock %}
  {% block footer %}
  {% endblock %}

sitio/templates/sitio/index.html
{% extends "base2.html" %}

sitio/templates/sitio/modal.html
{% load static %}
<div class="modal" id="ventanaModal" tabindex="-1" role="dialog" aria-labelledby="tituloVentana" aria-hidden="true">
    {% csrf_token %}
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            {% if obj %}
                <script>
                    alert("El objeto existe " + {{obj.name}})
                    
                </script>
            <div class="modal-header">
                <h5 id="tituloVentana">Detalle del Producto</h5>
                <button class="close" data-dismiss="modal" aria-label="Cerrar">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="alert alert-success">
                    <div id="content-wrapper">
                        <div class="column">
                            <img id="featured" src="{{product.imageURL}}">			
                            <div id="slide-wrapper">
                                <img id="slideLeft" class="arrow" src="{% static 'base/img/arrow-left.png' %}">
            
                                <div id="slider">
                                    {% for image in product.image_set.all%}					
                                        <img class="thumbnail" src="{{image.imageURL}}">
                                    {% endfor %}			
                                </div>
                                <img id="slideRight" class="arrow" src="{% static 'base/img/arrow-right.png' %}">
                            </div>
                        </div>			
                        <div class="column">
                            <h3>{{product.name}}</h3>
                            <hr>
                            <p>{{product.description}}</p>
                            <h4>₡{{product.price}}</h4>
                        </div>
                        <script type="text/javascript">
                                let thumbnails = document.getElementsByClassName('thumbnail')
                                let activeImages = document.getElementsByClassName('active')
                                for (var i=0; i < thumbnails.length; i++){
                                    thumbnails[i].addEventListener('mouseover', function(){
            
                                        if (activeImages.length > 0){
                                            activeImages[0].classList.remove('active')
                                        }
                                    
                                        this.classList.add('active')
                                        document.getElementById('featured').src = this.src
                                    })
                                }
            
                                const buttonRight = document.getElementById('slideRight');
                                const buttonLeft = document.getElementById('slideLeft');
            
            
                                buttonRight.addEventListener('click', function(){
                                    document.getElementById('slider').scrollLeft += 180;
                                })
            
                                buttonLeft.addEventListener('click', function(){
                                document.getElementById('slider').scrollLeft -= 180;
                                })
            
                        </script>
                    </div>
                </div>
            </div>
            {% endif %}

            <div class="modal-footer"> 
                <button class="btn btn-warning" type="button" data-dismiss="modal">
                    Cerrar
                </button>
                <button class="btn btn-success" type= "button">
                    Aceptar
                </button>
            </div>
        </div>
    </div>
</div>

sitio/templates/sitio/pos.html
{% extends 'base2.html' %}
{% load static %}


  {% block page_content %}
<div class="container-md pt-3">  
  <section>
    <div class="sectiontitle">
      <h6 class="heading">Adquiere nuestros productos en el punto más cercano</h6>
      <p>Contamos con los siguientes puntos de ventas.</p>
    </div>
    <div class="container-lg mb-2 bg-dark text-white">
      <div class="row">       
        {% for punto in puntosventas %}     
            <li class="one_third">
                <figure style="padding: 10px;">
                    <a href="#"><img src="{{punto.logo.url}}" style="image-align: center; width: 220px; height=110px;"  alt=""></a>
                <figcaption style="padding: 10px;">
                    <h6 class="heading" style="margin-left: 5px;">{{punto.name}}</h6>
                    <p style="margin-left: 5px;">Dirección: {{punto.direction}}</p>
                    <p style="margin-left: 5px;">Teléfono: {{punto.telephone}}</p>
                </figcaption>
                </figure>
            </li>
        {% endfor %}
      </div>
    </div>
  </section>
</div>
  {% endblock %}
  {% block footer %}
  {% endblock %}

sitio/templates/sitio/product.html
<!-- muestra la galeria de productos-->
{% extends 'base2.html' %}
{% load humanize %}
{% load static %}

{% block page_content %} 

<h3>Galeria de Productos</h3>
{% endblock %}

sitio/templates/sitio/products.html
{% extends 'base2.html' %}
{% load humanize %}
{% load static %}


{% block page_content %}
<div class="container-lg pt-2 bg-dark text-dark">
  <div class="row">   
	{% csrf_token %}     
	  {% for product in products %}     
		  <div class="col-4;">
			<div class="card ml-4 mr-2 mt-2 mb-2" style="width:25rem; height:35rem;">
				  <h4 class="card-title ml-2 mt-1">{{product.name}}</h4>
				  <img class="card-img-top ml-2 mt-2" src="{{product.imagen.url}}" alt="Card image" 
					style="max-width: 90%; align-self:center; height:50%; width:auto">
					<a class="btn btn-outline-dark btn-sm m-2" onclick="return abrir_modal('{% url 'sitio:ImagesProduct' product.id  %}')" href="#">
						<i class="fas fa-calendar-plus"></i> Ver
					</a>

					<label hidden="true" id="ID">{{product.id}}</label>
					<p class="limitado" style="margin-left: 5px;">{{product.description}}</p>
					<div class="row">
						<div style="margin-left: 25px;">
							PRECIO: ₡{{product.price}}
						</div>
					</div>
			  </div>
		  </div>
	  {% endfor %}
  </div>
</div>  
{% endblock %}
{% block footer %}
{% endblock footer %}

sitio/templates/sitio/productsimage.html
{% extends 'base2.html' %}
{% load static %}

{% block page_content %}
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div id="content-wrapper">
				<table>
					<tr>
						<td>
							<div class="column">
								<img id="featured" src="{{product.imageURL}}" style="height:300px; align-self:center;">
								<div id="slide-wrapper">
									<img id="slideLeft" class="arrow" src="{% static 'base/img/arrow-left.png' %}">			
									<div id="slider">
										{% for image in product.image_set.all%}					
											<img class="thumbnail" src="{{image.imageURL}}" style="height: 100px;">
										{% endfor %}			
									</div>
									<img id="slideRight" class="arrow" src="{% static 'base/img/arrow-right.png' %}">
								</div>
							</div>			
						</td>
						<td>
							<div class="column">
								<h4>{{product.name}}</h4>
								<hr>
								<p>{{product.description}}</p>
								
								<h4>Precio: ₡{{product.price}}</h4>
							</div>		
						</td>
					</tr>
				</table>	
				<button type="button" class="btn btn-success" onclick="return cerrar_modal()">Cerrar</button>
			</div>
		</div>
	</div>
	<script type="text/javascript">
		let thumbnails = document.getElementsByClassName('thumbnail')
		let activeImages = document.getElementsByClassName('active')
		for (var i=0; i < thumbnails.length; i++){
			thumbnails[i].addEventListener('mouseover', function(){

				if (activeImages.length > 0){
					activeImages[0].classList.remove('active')
				}
				this.classList.add('active')
				document.getElementById('featured').src = this.src
			})
		}
		const buttonRight = document.getElementById('slideRight');
		const buttonLeft = document.getElementById('slideLeft');

		buttonRight.addEventListener('click', function(){
			document.getElementById('slider').scrollLeft += 180;
		})

		buttonLeft.addEventListener('click', function(){
		document.getElementById('slider').scrollLeft -= 180;
		})
	</script>
{% endblock %}

sitio/templates/sitio/upload_image.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Upload Image</title>
</head>
<body>
</body>
</html>


{% extends 'pages\base.html' %}
{% load static %}


  {% block page_content %}

    <form action="{% url 'sitio:upload_image' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>
            <input id="id_image" type="file" accept="image/*" name="image" required>
        </p>
        <p>
            Image name:
            <input type="text" name="name" id="name" required>
        </p>
        <input type="submit" value="Submit"/>
    </form>

  {% endblock %}

  {% block footer %}
  {% endblock %}